services:

  flask_api:
    container_name: flask_api
    build: 
      context: ./flask_api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./flask_api:/app
    networks:
      - app-network

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: always
    command: redis-server --appendonly yes


  client:
    container_name: client
    build: 
      context: ./client/kotsek
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/kotsek:/app
    networks:
      - app-network
    depends_on:
      - flask_api

  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - client

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
    driver: local

