"""added incident table

Revision ID: 14cc09353dd5
Revises: eb32968e0c4a
Create Date: 2025-04-28 14:22:50.817992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14cc09353dd5'
down_revision: Union[str, None] = 'eb32968e0c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    op.alter_column('parking_sessions', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('vehicle_entries', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('vehicle_exits', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_exits', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('vehicle_entries', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('parking_sessions', 'plate_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('incident_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vehicles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='incidents_pkey')
    )
    # ### end Alembic commands ###
