"""another fix bs

Revision ID: a6f13be6486d
Revises: e509f8fe6382
Create Date: 2025-04-21 13:58:03.360071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f13be6486d'
down_revision: Union[str, None] = 'e509f8fe6382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'parking_slots', 'parking_lots', ['lot_id'], ['lot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parking_slots', type_='foreignkey')
    # ### end Alembic commands ###
