"""fix relationship issues Customer.lot_id

Revision ID: e509f8fe6382
Revises: 4bb6633c7e4c
Create Date: 2025-04-21 13:53:31.190036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e509f8fe6382'
down_revision: Union[str, None] = '4bb6633c7e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
