"""please

Revision ID: eb32968e0c4a
Revises: 5428f1702584
Create Date: 2025-04-22 21:27:12.520873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb32968e0c4a'
down_revision: Union[str, None] = '5428f1702584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('exit_id', sa.UUID(), nullable=True),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['parking_customers.customer_id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['vehicle_entries.entry_id'], ),
    sa.ForeignKeyConstraint(['exit_id'], ['vehicle_exits.exit_id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.lot_id'], ),
    sa.ForeignKeyConstraint(['plate_number'], ['parking_customers.plate_number'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.slot_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking_sessions')
    # ### end Alembic commands ###
