"""reupdate users table for is_blocked

Revision ID: f175a9e77412
Revises: a4d4a7f4766e
Create Date: 2025-05-17 20:01:59.690803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f175a9e77412'
down_revision: Union[str, None] = 'a4d4a7f4766e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'is_blocked')
    # ### end Alembic commands ###
